name: Deploy JoTravels Django App

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # ------------------------------------
    # Copy project files to EC2
    # ------------------------------------
    - name: Copy files to EC2 using SSH
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "."
        target: "~/jotravels-django-devops"

    # ------------------------------------
    # Run deploy.sh on EC2
    # ------------------------------------
    - name: Run deployment script on EC2
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ~/jotravels-django-devops
          chmod +x deploy.sh
          ./deploy.sh
